#!/usr/bin/env bash
# Copyright (c) 2021 The Toltec Contributors
# SPDX-License-Identifier: MIT

pkgnames=(toltecctl)
pkgdesc="Manage your Toltec install"
url=https://toltec-dev.org/
pkgver=0.0.0-1
timestamp=2021-03-08T13:28Z
section="utils"
maintainer="Eeems <eeems@eeems.email>"
license=MIT

source=(toltecctl)
sha256sums=(SKIP)

package() {
    install -D -m 744 -t "$pkgdir"/home/root/.local/bin "$srcdir"/toltecctl
}
