name: stable
on:
    push:
        branches:
            - stable
jobs:
    stable:
        name: Build and publish the stable channel
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Create Github Release
              continue-on-error: true
              uses: elgohr/Github-Release-Action@master
              env:
                GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
              with:
                args: "Automated Release on push to stable"
